# Generated by Django 4.2.6 on 2023-10-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('add', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
